### ISSUE TITLE
Node.js Website is right now surfacing Errors

### ISSUE THREAD

**Issue by TheBaldCoder** [nodejs/nodejs.org#5568]
### URL:

https://nodejs.org/en/download

### Browser Name:

Chrome

### Browser Version:

115.0.5790.110

### Operating System:

windows 11

### How to reproduce the issue:

I tried to go to the website: https://nodejs.org/en/download and keep getting this message:
![image](https://github.com/nodejs/nodejs.org/assets/128253003/20d5087f-83ac-477f-893b-c3216dbedc70)

![image](https://github.com/nodejs/nodejs.org/assets/128253003/d42fa5ab-2e27-4b40-b8e5-3900dc6bb00a)

I tried to disable my chrome extensions but those didn't seem to help.
All i want to do is download a new version of node.js

**Comment by umairraza96** [comment]
I can successfully reproduce it on Android

**Comment by gakuseh** [comment]
I am also having this issue on Windows 10 and iOS

**Comment by PrasathHari** [comment]
Meanwhile if you want to download, you can go to this page https://nodejs.org/download/release/
At the time of writing this the LTS version https://nodejs.org/download/release/latest-hydrogen/

**Comment by MattIPv4** [comment]
```
curl -I https://nodejs.org/static/js/legacyMain.js
HTTP/2 200 
date: Sun, 30 Jul 2023 15:51:51 GMT
content-length: 0
last-modified: Sun, 30 Jul 2023 14:36:50 GMT
cf-cache-status: HIT
age: 4282
expires: Sun, 30 Jul 2023 19:51:51 GMT
cache-control: public, max-age=14400
accept-ranges: bytes
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-content-type-options: nosniff
server: cloudflare
cf-ray: 7eeec3f1df2676ef-LHR
```

```
curl -I https://nodejs.org/static/js/legacyMain.js\?$(date +%s)
HTTP/2 200 
date: Sun, 30 Jul 2023 15:52:20 GMT
content-type: application/javascript; charset=utf-8
content-length: 2603
access-control-allow-origin: *
cache-control: public, max-age=14400
content-disposition: inline; filename="legacyMain.js"
etag: "0d5c446e1fe834ab661967503d5957e6"
strict-transport-security: max-age=31536000; includeSubDomains; preload
x-matched-path: /static/js/legacyMain.js
x-vercel-cache: HIT
x-vercel-id: gru1::87j2g-1690732340495-7bee204be7da
cf-cache-status: MISS
expires: Sun, 30 Jul 2023 19:52:20 GMT
accept-ranges: bytes
x-content-type-options: nosniff
server: cloudflare
cf-ray: 7eeec4a27d1d4133-LHR
```

**Comment by ovflowd** [comment]
Cloudflare cached this file precisely when Vercel was building the website, which is hilarious.

cc @nodejs/build-infra if anyone can please deploy this exact rule in Cloudflare Cache Rules:

![image](https://github.com/nodejs/nodejs.org/assets/12037269/320aa569-5717-4c7a-86be-35169d66061b)

URI Path regex is as `^/(dist|download|docs|api|documentation|metrics)/`

**Comment by egoroof** [comment]
> Node.js Website is right now surfacing Errors

the website is not working completely

**Comment by ovflowd** [comment]
> https://www.figma.com/file/pu1vZPqNIM7BePd6W8APA5/Node.js?type=design

Well, that's exactly what the description means.

**Comment by ovflowd** [comment]
We've deployed the changes on Cloudflare, and the Website is now back online! We apologize for these issues!

**Comment by umairraza96** [comment]
This issue still persists for me for some reason ![Screenshot_20230730-232631.png](https://github.com/nodejs/nodejs.org/assets/52033975/24aa502c-afe2-4861-9222-1c0f3a235d03)

**Comment by ovflowd** [comment]
@umairraza96 you seem to have a cached page. Cloudflare should already be purging this 😅
