### ISSUE TITLE
The table of contents does not work for translated pages for community package managers

### ISSUE THREAD

**Issue by stof** [nodejs/nodejs.org#6922]
### URL:

https://nodejs.org/fr/download/package-manager/all

### Browser Name:

Firefox

### Browser Version:

127.0.2

### Operating System:

Ubuntu 22.04

### How to reproduce the issue:

1. Click on the link `Debian et Distributions Linux basées sur Ubuntu` in the table of content
2. See that it does not scroll to the content

The table of content uses `#debian-and-ubuntu-based-linux-distributions` as anchor (using the English anchor) while the header uses `distributions-basées-sur-debian-et-ubuntu` as id (translating the anchor)

Some other anchors in that table of content are also impacted

**Comment by bmuenzenmeyer** [comment]
should be addressed via https://github.com/nodejs/nodejs.org/pull/6929

**Comment by stof** [comment]
@bmuenzenmeyer is this expected to be deployed already ? If yes, this is not fixed
