### ISSUE TITLE
Search is broken for certain articles

### ISSUE THREAD

**Issue by efekrskl** [nodejs/nodejs.org#8337]
### URL:

https://nodejs.org/en

### Browser Name:

Chrome

### Browser Version:

141.0.7390.123

### Operating System:

macOS Sequoia

### How to reproduce the issue:

1) Go to https://nodejs.org/en
2) Click on search bar (`Start typing...`)
3) Search for `Memory` (as in the Memory article https://nodejs.org/en/learn/diagnostics/memory)
4) Instead of navigating to the URL above, you'll get forwarded to `https://nodejs.org/en/learn/diagnostics/memory/index#memory`

It looks like this is because these articles are named as `index.md` instead of an actual slug. This means:

- `live-debugging`
- `poor-performance`
- `memory`

should have the same bug

**Comment by bmuenzenmeyer** [comment]
good report - thanks for this. 
we do have some plans to change learn content as a result of nodejs/learn#40 or nodejs/nodejs.org#8272 - but we should resolve this in production too.

@micheleriva is this anything on your end that we should be aware of?

**Comment by micheleriva** [comment]
Hi @bmuenzenmeyer, @efekrskl we have a PR open (#8175) that moves the whole search infra to the new Orama Cloud. Can you please test if here it is working as expected? Node.js is currently on an old infra (with an old version of Orama) and all the fixes will be deployed in the new one - except, of course, if search is severely broken!

In this report it looks like the problem is with syncing data rather than accessing it. This should also be solved in nodejs/nodejs.org#8175, which should be ready to be merged per the last comments (@ovflowd)

**Comment by efekrskl** [comment]
Yes, this issue still persists [in the Preview](https://nodejs-6lwi6dimb-openjs.vercel.app/en) of nodejs/nodejs.org#8175

As mentioned in the issue body, this is somehow related to the filenames. I didn't have time to do a deep dive though

**Comment by micheleriva** [comment]
Oh Gosh you're right sorry - I misinterpreted the issue when I first read it. It does look like the problem is with file names - especially with `index.md` ones. Should be an easy fix though. Let me check this in nodejs/nodejs.org#8175.

**Comment by efekrskl** [comment]
This issue is resolved
